### ISSUE TITLE
[App] Adding event listener to ReactDom insted of passing OnClick handler as props

### ISSUE THREAD

**Issue by heyapricot** [zlayabekrija/react-calculator#3]
I see no reason to add a click event listener to the ReactDOM instead of passing OnClick as props? This is not right

**Comment by inhaq** [comment]
Will you please explain why event delegation is wrong in React?

**Comment by heyapricot** [comment]
The Milestone 5 states the following:
> App
Implement the handleClick function which takes buttonName as an argument and changes the state based on the result of the calculate function.
Pass handleClick as a clickHandler property to ButtonPanel

> ButtonPanel
    Implement the handleClick function which takes buttonName as an argument and returns clickHandler from props.
    Pass the clickHandler property to each button in the panel.

> Button 
Implement the handleClick function which takes buttonName as an argument and returns clickHandler from props.
Use the onClick event to attach the handleClick event to the button.

What the assignment is looking for is for you to define a handleClick function in App.js and then pass that function as a prop to the ButtonPanel component which will subsequently will pass it as a prop to the Button component. The assignment adds a link on how to do this. Feel free to reach out for further clarification

https://reactjs.org/docs/events.html#mouse-events

**Comment by zlayabekrija** [comment]
Done 😄
